yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        views.AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        views.AboutTechView.as_view(),
        name='tech'
    ),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'Posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'group/<slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.create_post,
        name='create_post'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(
        '',
        include(
            'posts.urls',
            namespace='posts'
        )
    ),
    path(
        'about/',
        include(
            'about.urls',
            namespace='about'
        )
    ),
    path(
        'admin/',
        admin.site.urls
    ),
    path(
        'auth/',
        include(
            'users.urls',
            namespace='users'
        )
    ),
    path(
        'auth/',
        include('django.contrib.auth.urls')
    ),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel
from django.db.models import UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Название группы',
        max_length=200
    )
    slug = models.SlugField(
        'Идентификатор группы',
        max_length=200,
        unique=True
    )
    description = models.TextField('Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='order_group_posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )


class Meta:
    ordering = ('pub_date',)
    verbose_name = 'Пост'
    verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        'Комментарий',
        help_text='Введите текст комментария'
    )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    def __str__(self):
        return self.author

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=~models.Q(
                    user=models.F('author')),
                name='self-subscription_not_allowed'),
            UniqueConstraint(
                fields=['user', 'author'],
                name='unique_users'
            ),
        ]

yatube/posts/forms.py
from django import forms

from .models import Group, Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'text',
            'group',
            'image'
        )

        text = forms.Textarea()
        group = forms.ModelChoiceField(
            queryset=Group.objects.all(),
            required=False
        )
        image = forms.ImageField()


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        text = forms.Textarea()

yatube/posts/views.py
from http import HTTPStatus

from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
# from django.core.mail import send_mail
from django.urls import reverse_lazy

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow


def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    text = 'Последние обновления на сайте'
    image = Post.image
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.NUMBER_OF_POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': title,
        'text': text,
        'image': image,
    }
    return render(
        request,
        template,
        context
    )


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.order_group_posts.all()
    paginator = Paginator(post_list, settings.NUMBER_OF_POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    image = Post.image
    context = {
        'group': group,
        'page_obj': page_obj,
        'image': image,
    }
    return render(
        request,
        template,
        context
    )


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    title = 'Профайл пользователя ' + author.get_full_name()
    post_list = author.posts.all()
    paginator = Paginator(post_list, settings.NUMBER_OF_POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    image = Post.image
    current_user = request.user
    if current_user.is_authenticated and current_user != author:
        following = Follow.objects.filter(
            user=current_user, author=author).exists()
    else:
        following = False
    context = {
        'page_obj': page_obj,
        'title': title,
        'author': author,
        'post_list': post_list,
        'image': image,
        'following': following,
    }
    return render(request,
                  template,
                  context
                  )


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = Post.objects.filter(pk=post_id).first()
    title = 'Пост ' + post.text[:15]
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    image = Post.image
    context = {
        'post': post,
        'form': form,
        'comments': comments,
        'title': title,
        'image': image,
    }
    return render(request,
                  template,
                  context
                  )


@login_required
def create_post(request):
    template = 'posts/create_post.html'
    title = 'Новая запись'
    header = 'Добавить запись'
    form = PostForm(data=request.POST or None,
                    files=request.FILES or None)
    id_group = Group.objects.all()
    if request.method == 'POST':

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect(
                reverse_lazy(
                    'posts:profile',
                    args=(request.user.username,)
                )
            )
        else:
            form = render(request,
                          template,
                          {'form': form}
                          )

    context = {
        'title': title,
        'header': header,
        'id_group': id_group,
        'form': form,
    }
    return render(
        request,
        template,
        context
    )


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html',
    title = 'Редактировать запись'
    header = 'Редактировать запись'
    post = get_object_or_404(
        Post,
        pk=post_id
    )

    if post.author != request.user:
        return redirect(reverse_lazy(
            'posts:post_detail',
            args=(post.pk,)))

    if request.method == 'POST':
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post
        )
        if form.is_valid():
            form.save()
            return redirect(
                reverse_lazy(
                    'posts:post_detail',
                    args=(post.pk,))
            )
        else:
            return render(
                request,
                template,
                {'form': form}
            )

    form = PostForm(initial={'text': post.text})
    context = {
        'title': title,
        'header': header,
        'post_edit': True,
        'form': form,
    }
    return render(
        request,
        template,
        context
    )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post.pk)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    current_user = request.user
    title = 'Подписки'
    text = 'Посты по подпискам'
    post_list = Post.objects.filter(
        author__following__user=current_user)
    paginator = Paginator(post_list, settings.NUMBER_OF_POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': title,
        'text': text,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user, author=author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.filter(
            user=request.user, author=author
        ).delete()
    return redirect('posts:profile', username=author.username)

yatube/templates/posts/create.html
{% extends 'base.html' %}
{% include 'includes/header.html' %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">

          <div class="card-header">
            {{ header }}
          </div>

          <div class="card-body">
            {% if is_edit %}
              <form method="post">
            {% else %}
              <form method="post" action="{% url 'posts:post_create' %}">
            {% endif %}
            {% csrf_token %}

            {{ form.as_p }}
            <small id="id_group-help" class="form-text text-muted">
              Группа, к которой будет относиться пост
            </small>

            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% include 'includes/footer.html' %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% include 'includes/header.html' %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">

          <div class="card-header">
            {{ header }}
          </div>

          <div class="card-body">
            {% if post_edit %}
              <form method="post" enctype="multipart/form-data">
            {% else %}
              <form method="post" enctype="multipart/form-data"
                    action="{% url 'posts:create_post' %}">
            {% endif %}
            {% csrf_token %}

            {{ form.as_p }}
            <small id="id_group-help" class="form-text text-muted">
              Группа, к которой будет относиться пост
            </small>

            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if post_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% include 'includes/footer.html' %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% include 'includes/header.html' %}

{% load thumbnail %}
{% load static %}

{% block content %}
  <h1>{{ text }}</h1>
  {% include 'includes/switcher.html' %}

  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a
              href="{% url 'Posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>

      {% thumbnail post.image "100x100" crop="center" as im %}
        <img src="/media/{{ post.image }}" width="960" height="399"
             alt="">
      {% endthumbnail %}
        <p>{{ post.text|linebreaksbr }}</p>

      <a class="navbar-brand"
         href="{% url 'Posts:post_detail' post.pk %}">
        подробная информация
      </a>

      {% if post.group %}
        <a class="navbar-brand"
           href="{% url 'Posts:group_list' post.group.slug %}">
          всё записи группы
        </a>
      {% endif %}
    </article>

    {% if not forloop.last %}
      <hr>{% endif %}

  {% endfor %}

  {% include 'includes/paginator.html' %}


{% endblock %}

{% include 'includes/footer.html' %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% include 'includes/header.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}

  <h1>{{ group.title }}</h1>
  <p> {{ group.description|linebreaksbr }} </p>

  {% for post in page_obj %}
    <ul>
      <li> Автор: {{ post.author.get_full_name }} </li>
      <li> Дата публикации: {{ post.pub_date|date:"d E Y" }} </li>
    </ul>
    {% thumbnail post.image "100x100" crop="center" as im %}
      <img src="/media/{{ post.image }}" width="960" height="399"
           alt="">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}
      <hr>{% endif %}
  {% endfor %}

  {% include 'includes/paginator.html' %}

{% endblock %}
{% include 'includes/footer.html' %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% include 'includes/header.html' %}

{% load thumbnail %}
{% load static %}
{% load cache %}

{% block content %}
  {% cache 20 index_page with page_obj %}
    <h1>{{ text }}</h1>
    {% include 'includes/switcher.html' %}

    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a
              href="{% url 'Posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
        <li> Дата публикации: {{ post.pub_date|date:"d E Y" }} </li>
      </ul>

      {% thumbnail post.image "100x100" crop="center" as im %}
        <img src="/media/{{ post.image }}" width="960" height="399"
             alt="">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>

      <a class="navbar-brand"
         href="{% url 'Posts:post_detail' post.pk %}">
        подробная информация
      </a>

      {% if post.group %}
        <a class="navbar-brand"
           href="{% url 'Posts:group_list' post.group.slug %}">
          всё записи группы
        </a>
      {% endif %}

      {% if not forloop.last %} <hr> {% endif %}

    {% endfor %}

    {% include 'includes/paginator.html' %}

  {% endcache %}

{% endblock %}

{% include 'includes/footer.html' %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% include 'includes/header.html' %}

{% block content %}

  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">

        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>

        <!-- если у поста есть группа -->
        <li class="list-group-item">
          Группа: {{ post.group.get_full_name }}
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          {% endif %}
        </li>

        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>

        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span> {{ post.author.posts.count }} </span>
        </li>

        <li class="list-group-item">
          {% if post.author.username is not None %}
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          {% endif %}
        </li>

      </ul>
    </aside>

    <article class="col-12 col-md-9">
      {% thumbnail post.image "100x100" crop="center" as im %}
        <img src="/media/{{ post.image }}" width="960" height="399" alt="">
      {% endthumbnail %}
      <p> {{ post.text|linebreaksbr }} </p>
    </article>

    {% if post.author.username == user.username %}
      <form action="{% url 'posts:post_edit' post.pk %}">
        <button type="submit" class="btn btn-primary">
          редактировать запись
        </button>
      </form>
    {% endif %}

 {% include 'includes/post_comment.html' %}

  </div>

{% endblock %}

{% include 'includes/footer.html' %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% include 'includes/header.html' %}
{% block title %}

{% endblock %}
{% block content %}

  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3>

  {% if following %}
    <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}"
        role="button"
    >
      Отписаться
    </a>
  {% else %}
    <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}"
        role="button"
    >
      Подписаться
    </a>
  {% endif %}

  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ author.username }}
          <a
              href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>

      {% thumbnail post.image "100x100" crop="center" as im %}
        <img src="/media/{{ post.image }}" width="960" height="399"
             alt="">
      {% endthumbnail %}
      <p> {{ post.text|linebreaksbr }} </p>

      <a class="navbar-brand"
         href="{% url 'Posts:post_detail' post.pk %}">
        подробная информация
      </a>

      {% if post.group %}
        <a class="navbar-brand"
           href="{% url 'Posts:group_list' post.group.slug %}">
          все записи группы
        </a>
      {% endif %}
    </article>
    {% if not forloop.last %}
      <hr>{% endif %}
  {% endfor %}

  {% include 'includes/paginator.html' %}

{% endblock %}

{% include footer.html %}